/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.menus;

import business.Facade;

/**
 *
 * @author Luís Alves
 */
public class MenuEscolha extends javax.swing.JFrame {

    private Facade f;
    
    private void centerFrame() {
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    
    /**
     * Creates new form MenuEscolha
     */
    public MenuEscolha(Facade f) {
        this.f = f;
        initComponents();
        this.centerFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    configura = new javax.swing.JButton();
    acessorio = new javax.swing.JButton();
    pacote = new javax.swing.JButton();
    concluir = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    configura.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
    configura.setText("Configuração ótima");
    configura.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        configuraActionPerformed(evt);
      }
    });

    acessorio.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
    acessorio.setText("Acessórios");
    acessorio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    acessorio.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        acessorioActionPerformed(evt);
      }
    });

    pacote.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
    pacote.setText("Pacote Pré-Configurado");
    pacote.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        pacoteActionPerformed(evt);
      }
    });

    concluir.setText("Concluir");
    concluir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        concluirActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(12, 12, 12)
        .addComponent(acessorio, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(configura, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(pacote, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(concluir, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(65, 65, 65)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(acessorio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(configura, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(pacote, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
        .addComponent(concluir, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(33, 33, 33))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void acessorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acessorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acessorioActionPerformed

    private void configuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configuraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_configuraActionPerformed

    private void pacoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pacoteActionPerformed

  private void concluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concluirActionPerformed
    this.dispose();
    (new MenuFinal(f)).setVisible(true);
  }//GEN-LAST:event_concluirActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton acessorio;
  private javax.swing.JButton concluir;
  private javax.swing.JButton configura;
  private javax.swing.JButton pacote;
  // End of variables declaration//GEN-END:variables
}
