/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.configotima;

import business.Componente;
import business.Facade;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JPanel;
import view.menus.MenuEscolha;

/**
 *
 * @author Luís Alves
 */
public class InsereValorObjetivo extends javax.swing.JPanel {

    private Facade facade;
    private SelecionaConfiguracaoOtima parent;
    private JPanel cardPanel;
    /**
     * Creates new form InsereValorObjetivo
     */
    public InsereValorObjetivo(Facade f, SelecionaConfiguracaoOtima s) {
        facade = f;
        parent = s;
        cardPanel = s.getCardPanel();
        initComponents();
        this.parent.setTitle("Insere valor objetivo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    labelValor = new javax.swing.JLabel();
    valorField = new javax.swing.JTextField();
    cancelarButton = new javax.swing.JButton();
    calcularButton = new javax.swing.JButton();

    setMaximumSize(new java.awt.Dimension(400, 300));
    setMinimumSize(new java.awt.Dimension(400, 300));

    labelValor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    labelValor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    labelValor.setText("Valor a otimizar");

    valorField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

    cancelarButton.setText("Cancelar");
    cancelarButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelarButtonActionPerformed(evt);
      }
    });

    calcularButton.setText("Calcular");
    calcularButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        calcularButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(146, 146, 146)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(labelValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(valorField))
        .addGap(147, 147, 147))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(20, 20, 20))
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
          .addGap(20, 20, 20)
          .addComponent(calcularButton, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
          .addGap(249, 249, 249)))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(96, 96, 96)
        .addComponent(labelValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(valorField, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        .addGap(74, 74, 74)
        .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(21, 21, 21))
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
          .addContainerGap(226, Short.MAX_VALUE)
          .addComponent(calcularButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(21, 21, 21)))
    );
  }// </editor-fold>//GEN-END:initComponents

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        this.parent.dispose();
        (new MenuEscolha(facade)).setVisible(true);
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void calcularButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularButtonActionPerformed
      String valueS = this.valorField.getText();
      double value = 0;
      try {
        value = Double.parseDouble(valueS);
      }
      catch (NumberFormatException e) {
      }
      if (value != 0) {
        List<Componente> comps = this.facade.getConfiguracaoOtima(value);
        facade.adicionaCompTemporario(comps);
        cardPanel.add(new ListaSugeridos(facade, parent,comps), "LISTA");
        CardLayout cl = (CardLayout) cardPanel.getLayout();
        cl.show(cardPanel, "LISTA");
      }
    }//GEN-LAST:event_calcularButtonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton calcularButton;
  private javax.swing.JButton cancelarButton;
  private javax.swing.JLabel labelValor;
  private javax.swing.JTextField valorField;
  // End of variables declaration//GEN-END:variables
}
