/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.componenteprimario;

import business.Componente;
import business.ComponentePrimario;
import business.Facade;
import business.Modelo;
import java.awt.CardLayout;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JList;
import javax.swing.JPanel;
import view.menus.MenuPrincipal;

/**
 *
 * @author Luís Alves
 */
public class ListaPrimariosSelecionaveis extends javax.swing.JPanel {

    private Facade facade;
    private SelecionaComponentePrimario parent;
    private JPanel cardPanel;
    
    /**
     * Creates new form ListaPrimariosSelecionaveis
     */
  public ListaPrimariosSelecionaveis(Facade f, SelecionaComponentePrimario parent) {
    this.facade = f;
    this.parent = parent;
    this.cardPanel = parent.getCardPanel();
    initComponents();
    this.parent.setTitle("Componentes Selecionáveis");
    List<ComponentePrimario> primario = facade.getPrimariosSelecionaveis();
    String[] comps = new String[primario.size()];
    for (int i = 0; i < comps.length; i++) {
      comps[i] = primario.get(i).getName();
    }
    listaComponentes.setModel(new javax.swing.AbstractListModel<String>() {
      String[] strings = comps;

      public int getSize() {
        return strings.length;
      }

      public String getElementAt(int i) {
        return strings[i];
      }
    });
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    scrollListaModelos = new javax.swing.JScrollPane();
    listaModelos = new javax.swing.JList<>();
    butaoSair = new javax.swing.JButton();
    butaoSelecionar = new javax.swing.JButton();
    labelComponentes = new javax.swing.JLabel();
    labelModelos = new javax.swing.JLabel();
    scrollListaComponentes = new javax.swing.JScrollPane();
    listaComponentes = new javax.swing.JList<>();

    listaModelos.setModel(new javax.swing.AbstractListModel<String>() {
      String[] strings = {};
      public int getSize() { return strings.length; }
      public String getElementAt(int i) { return strings[i]; }
    });
    listaModelos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
      public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
        listaModelosValueChanged(evt);
      }
    });
    scrollListaModelos.setViewportView(listaModelos);

    butaoSair.setText("Sair");
    butaoSair.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        butaoSairActionPerformed(evt);
      }
    });

    butaoSelecionar.setText("Selecionar");
    butaoSelecionar.setEnabled(false);
    butaoSelecionar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        butaoSelecionarActionPerformed(evt);
      }
    });

    labelComponentes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    labelComponentes.setText("Componentes");

    labelModelos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    labelModelos.setText("Modelos");

    listaComponentes.setModel(new javax.swing.AbstractListModel<String>() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public String getElementAt(int i) { return strings[i]; }
    });
    listaComponentes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
      public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
        listaComponentesValueChanged(evt);
      }
    });
    scrollListaComponentes.setViewportView(listaComponentes);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(34, 34, 34)
            .addComponent(scrollListaComponentes, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addGap(60, 60, 60)
            .addComponent(labelComponentes)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(labelModelos)
            .addGap(86, 86, 86))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(scrollListaModelos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(layout.createSequentialGroup()
                .addComponent(butaoSelecionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(37, 37, 37))))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(30, 30, 30)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelComponentes)
          .addComponent(labelModelos))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addComponent(scrollListaModelos, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addComponent(scrollListaComponentes)))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(butaoSair)
          .addComponent(butaoSelecionar))
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

    private void butaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaoSairActionPerformed
        this.parent.dispose();
        this.facade.cancelaConfiguracao();
        (new MenuPrincipal(facade)).setVisible(true);
    }//GEN-LAST:event_butaoSairActionPerformed

    private void butaoSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaoSelecionarActionPerformed

      int comp = listaComponentes.getSelectedIndex();
      int mod = listaModelos.getSelectedIndex();
      CardLayout cl = (CardLayout) cardPanel.getLayout();
      ComponentePrimario prim = facade.getPrimariosSelecionaveis().get(comp);
      Modelo modelo = facade.getModelo(prim.getModelos().get(mod));
      List<Componente> extra = facade.getExtra(modelo.getCod());
      List<Componente> incompatible = facade.getIncompativeis(modelo.getCod());
      if (extra.size() > 0) {
        cardPanel.add(new ListaPrimariosExtra(facade, parent), "EXTRA");
        cl.show(cardPanel, "EXTRA");
      } else if (incompatible.size() > 0) {
        cardPanel.add(new ListaPrimariosIncompativeis(facade, parent), "INCOMPATIVEL");
        cl.show(cardPanel, "INCOMPATIVEL");
      } else {
        cardPanel.add(new ApresentaPrecoPrimario(facade, parent), "PRECO");
        cl.show(cardPanel, "PRECO");
      }
    }//GEN-LAST:event_butaoSelecionarActionPerformed

  private void listaComponentesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaComponentesValueChanged
    if (!evt.getValueIsAdjusting()) {
      int row = listaComponentes.getSelectedIndex();
      List<ComponentePrimario> selecionaveis = facade.getPrimariosSelecionaveis();
      ComponentePrimario c = selecionaveis.get(row);

      List<Modelo> modelos = facade.getModelos(c.getCod());
      String[] mods = new String[modelos.size()];
      for (int i = 0; i < mods.length; i++) {
        mods[i] = modelos.get(i).getName();
      }
      listaModelos.setModel(new javax.swing.AbstractListModel<String>() {
        String[] strings = mods;

        public int getSize() {
          return strings.length;
        }

        public String getElementAt(int i) {
          return strings[i];
        }
      });
    }
    
  }//GEN-LAST:event_listaComponentesValueChanged

  private void listaModelosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaModelosValueChanged
    if (!evt.getValueIsAdjusting()) {
      butaoSelecionar.setEnabled(true);
    }
  }//GEN-LAST:event_listaModelosValueChanged


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton butaoSair;
  private javax.swing.JButton butaoSelecionar;
  private javax.swing.JLabel labelComponentes;
  private javax.swing.JLabel labelModelos;
  private javax.swing.JList<String> listaComponentes;
  private javax.swing.JList<String> listaModelos;
  private javax.swing.JScrollPane scrollListaComponentes;
  private javax.swing.JScrollPane scrollListaModelos;
  // End of variables declaration//GEN-END:variables
}
