/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.componenteprimario;

import business.Facade;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Luís Alves
 */
public class ListaComponentesPrimariosExtra extends javax.swing.JFrame {

    private Facade facade;
    /**
     * Creates new form ListaComponentesPrimariosExtra
     */
    public ListaComponentesPrimariosExtra(Facade f) {
        this.facade = f;
        initComponents();
        this.setResizable(false);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelComponentesExtra = new javax.swing.JLabel();
        labelModelosExtra = new javax.swing.JLabel();
        scrollListaComponentesExtra = new javax.swing.JScrollPane();
        listaComponentesExtra = new javax.swing.JList<>();
        scrollListaModelosExtra = new javax.swing.JScrollPane();
        listaModelosExtra = new javax.swing.JList<>();
        butaoCancelar = new javax.swing.JButton();
        butaoAdicionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Componente Primário Requer Extra"); // NOI18N

        labelComponentesExtra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelComponentesExtra.setText("Componentes Extra");

        labelModelosExtra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelModelosExtra.setText("Modelos Extra");

        listaComponentesExtra.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollListaComponentesExtra.setViewportView(listaComponentesExtra);

        listaModelosExtra.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollListaModelosExtra.setViewportView(listaModelosExtra);

        butaoCancelar.setText("Cancelar");
        butaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaoCancelarActionPerformed(evt);
            }
        });

        butaoAdicionar.setText("Adicionar");
        butaoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaoAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(labelComponentesExtra)
                            .addComponent(scrollListaComponentesExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(scrollListaModelosExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelModelosExtra)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(197, Short.MAX_VALUE)
                        .addComponent(butaoAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butaoCancelar)))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelComponentesExtra)
                    .addComponent(labelModelosExtra))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(scrollListaModelosExtra, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(scrollListaComponentesExtra)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butaoCancelar)
                    .addComponent(butaoAdicionar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaoCancelarActionPerformed
        this.dispose();
        facade.cancelaPrimario();
        //(new ListaComponentesPrimariosSelecionados(facade)).setVisible(true);
        
    }//GEN-LAST:event_butaoCancelarActionPerformed

    private void butaoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaoAdicionarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        (new ListaComponentesPrimariosIncompativeis(facade)).setVisible(true);
    }//GEN-LAST:event_butaoAdicionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butaoAdicionar;
    private javax.swing.JButton butaoCancelar;
    private javax.swing.JLabel labelComponentesExtra;
    private javax.swing.JLabel labelModelosExtra;
    private javax.swing.JList<String> listaComponentesExtra;
    private javax.swing.JList<String> listaModelosExtra;
    private javax.swing.JScrollPane scrollListaComponentesExtra;
    private javax.swing.JScrollPane scrollListaModelosExtra;
    // End of variables declaration//GEN-END:variables
}
