/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.pacote;

import business.Componente;
import business.Facade;
import business.Pacote;
import java.util.List;
import javax.swing.JPanel;
import view.menus.MenuEscolha;

/**
 *
 * @author Luís Alves
 */
public class ApresentaPrecoPacote extends javax.swing.JPanel {

  private Facade facade;
  private SelecionaPacote parent;
  private JPanel cardPanel;
  private Pacote pack;
  
  /**
   * Creates new form ApresentaPrecoPacote
   */
  public ApresentaPrecoPacote(Facade f, SelecionaPacote par, Pacote pack) {
    initComponents();
    this.facade = f;
    this.parent = par;
    this.cardPanel = parent.getCardPanel();
    this.pack = pack;
    double priceNoDisc = pack.getComponentes().stream().mapToDouble(c -> c.getPrice()).sum();
    double priceDisc = pack.getPreco();
    this.precoSemPack.setText(priceNoDisc + "");
    this.precoPack.setText(priceDisc +"");
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    confirmarButton = new javax.swing.JButton();
    cancelarButton = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    precoSemPack = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    precoPack = new javax.swing.JLabel();

    confirmarButton.setText("Confirmar");
    confirmarButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        confirmarButtonActionPerformed(evt);
      }
    });

    cancelarButton.setText("Cancelar");
    cancelarButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelarButtonActionPerformed(evt);
      }
    });

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel1.setText("Preço normal");

    precoSemPack.setBackground(new java.awt.Color(255, 255, 255));
    precoSemPack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    precoSemPack.setText("jLabel2");
    precoSemPack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    precoSemPack.setOpaque(true);

    jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel3.setText("Preço pacote");

    precoPack.setBackground(new java.awt.Color(255, 255, 255));
    precoPack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    precoPack.setText("jLabel2");
    precoPack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    precoPack.setOpaque(true);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(28, 28, 28)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addComponent(precoSemPack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addComponent(precoPack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(confirmarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cancelarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(43, 43, 43))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(68, 68, 68)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(precoSemPack, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(confirmarButton))
        .addGap(31, 31, 31)
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(precoPack, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(cancelarButton))
        .addContainerGap(107, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void confirmarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarButtonActionPerformed
    this.facade.confirmaComponentes();
    this.parent.dispose();
    (new MenuEscolha(facade)).setVisible(true);
  }//GEN-LAST:event_confirmarButtonActionPerformed

  private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
    this.facade.cancelaConfiguracao();
    this.parent.dispose();
    (new MenuEscolha(facade)).setVisible(true);
  }//GEN-LAST:event_cancelarButtonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelarButton;
  private javax.swing.JButton confirmarButton;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel precoPack;
  private javax.swing.JLabel precoSemPack;
  // End of variables declaration//GEN-END:variables
}
