/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.componenteacessorio;

import business.Facade;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author grupo
 */
public class PrecoFinalDoAcessorio extends javax.swing.JPanel {

    private Facade facade;
    private SelecionaComponenteAcessorio parent;
    private JPanel cardPanel;
    private int componente;
    
    public PrecoFinalDoAcessorio(Facade f, SelecionaComponenteAcessorio parent,int escolhido) {
        this.facade=f;
        this.parent=parent;
        this.componente= escolhido;
        this.cardPanel=parent.getCardPanel();
        initComponents();
        double tempPrice = facade.getPrecoTemporario();
        preço.setText(tempPrice + "");
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    preçoTexto = new javax.swing.JLabel();
    confirmar = new javax.swing.JButton();
    cancelar = new javax.swing.JButton();
    preço = new javax.swing.JLabel();

    preçoTexto.setFont(new java.awt.Font("Oriya Sangam MN", 1, 18)); // NOI18N
    preçoTexto.setText("       Preço:");

    confirmar.setText("Confirmar");
    confirmar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        confirmarActionPerformed(evt);
      }
    });

    cancelar.setText("Cancelar");
    cancelar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelarActionPerformed(evt);
      }
    });

    preço.setBackground(new java.awt.Color(255, 255, 255));
    preço.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    preço.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    preço.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    preço.setOpaque(true);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addComponent(confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(65, 65, 65)
            .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addGap(141, 141, 141)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
              .addComponent(preço, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(preçoTexto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addGap(10, 10, 10))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(62, 62, 62)
        .addComponent(preçoTexto)
        .addGap(18, 18, 18)
        .addComponent(preço, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(49, 49, 49)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(46, 46, 46))
    );
  }// </editor-fold>//GEN-END:initComponents

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        this.facade.confirmaComponentes();
        cardPanel.add(new ListaComponentes(facade, parent), "ACESSORIOS");
        CardLayout cl = (CardLayout) cardPanel.getLayout();
        cl.show(cardPanel, "ACESSORIOS");
    }//GEN-LAST:event_confirmarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.facade.cancelaConfiguracao();
        cardPanel.add(new ListaComponentes(facade, parent), "ACESSORIOS");
        CardLayout cl = (CardLayout) cardPanel.getLayout();
        cl.show(cardPanel, "ACESSORIOS");
    }//GEN-LAST:event_cancelarActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelar;
  private javax.swing.JButton confirmar;
  private javax.swing.JLabel preço;
  private javax.swing.JLabel preçoTexto;
  // End of variables declaration//GEN-END:variables
}
